### ISSUE TITLE
Add support for YouCompleteMe+ccls

### ISSUE THREAD

**Issue by jbarik** [m-pilia/vim-ccls#27]
I currently use YouCompleteMe + ccls. It would be great if this plugin can support YouCompleteMe.

**Comment by m-pilia** [comment]
Hi @jbarik!

In order to interact with ccls, vim-ccls requires an LSP client that is able to send custom requests to the server (such as the plugins mentioned in the README), since features such as inheritance or call hierarchies are a non-standard language server API that is specific to ccls. As far as I know, YouCompleteMe does not expose an API to send custom LSP requests to the server, so unfortunately it is not possible to use it as a backend for vim-ccls.

**Comment by jbarik** [comment]
Thanks for looking into it. Unfortunate that YouCompleteMe doesn't expose any API.
