### ISSUE TITLE
Support for `textDocument/documentSymbol`

### ISSUE THREAD

**Issue by lanza** [m-pilia/vim-ccls#34]
This would duplicate the functionality from Vista, however I prefer the vim-ccls float window implementation for most purposes. I tried getting this to work but I can't figure out the `a:data` parameter that vim-yggdrasil requires. `CocRequest` for `textDocument/documentSymbol` gives back a vim list. Some data massaging will have to be done to get it in the right form. That or vim-yggdrasil has to learn how to accept lists.

**Comment by m-pilia** [comment]
I had a quick look, the `textDocument/documentSymbol` has a slightly different schema and it is not compatible out-of-the-box with `$ccls/member`, but it should be easy to support it.

I did not add this before because `textDocument/documentSymbol` is a standart LSP methods, not a ccls-specific feature, so strictly speaking it would be out of the scope of this plugin. But I like the idea of having a hierarchical view of the document symbols that is consistent with the other hierarchies, so I will look into implementing this.
