### ISSUE TITLE
Optionally show previews in a split/popup

### ISSUE THREAD

**Issue by lanza** [m-pilia/vim-ccls#41]
Pretty simple idea -- if you're in a vim-ccls pane and hit `p` it'll toggle showing a preview in a `vsplit` of the location of the current highlighted line.

```
class Base {}
class Sub1 : public Base {}
case Sub2 : public Base {}
```

Calling `CclsDerivedHierarchy` on `Base` will yield

```
V Base
   * Sub1
   * Sub2     <---- cursor
```

and with the cursor on `Sub2` it'll call `vsplit lib/File/Sub2.cpp`.

**Comment by m-pilia** [comment]
Hi @lanza and thank you for writing this issue. If I understand this correctly, your idea would be to have something conceptually similar to VSCode's preview with CodeLens.

I like the idea and I can look into this (unfortunately I can't promise anything fast because I have a quite dense schedule right now). Some of the LSP plugins used as backend of vim-ccls already integrate a CodeLens-like preview feature, so I can check if it is possible to integrate this in some way or if it will require a completely standalone implementation.

**Comment by lanza** [comment]
My sample implementation works and is stable, it just leaves the pane open. You can check that out for a demo.
