### ISSUE TITLE
how to disable on runtime

### ISSUE THREAD

**Issue by windrg** [m-pilia/vim-ccls#60]
Hi,
I appreciate your great work.
However I feel uncomfortable when I'm using vimdiff.
Whenever I launch vimdiff, it tries to run ccls in the background.
And sometimes I feel that it gets sluggish in my big project. Thus I wonder if there is a method how to disable this plugin from working on  runtime. I think it would be nice to provide an API eg CclsDisable

**Comment by m-pilia** [comment]
Hi @windrg, and thanks for the message!

I should clarify that `vim-ccls` never starts `ccls` by itself. The server is started and managed by the language client that you are using as backend, and `vim-ccls` will only send requests to the server through the API of the language client, and only when you explicitly run any `CclsX` command.

I do not know what language client you are using, but it has to be one from the list on top of the README:

- [ALE](https://github.com/w0rp/ale)
- [coc.nvim](https://github.com/neoclide/coc.nvim)
- [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim)
- [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig)
- [vim-lsc](https://github.com/natebosch/vim-lsc)
- [vim-lsp](https://github.com/prabirshrestha/vim-lsp)

Therefore, in order to fix the issue with `ccls` running when you do not want to, you should check the documentation and the configuration of your language client.

**Comment by windrg** [comment]
Thanks for your answer. Then I need to contact vim-lsp. 
Thanks again.
